### ISSUE TITLE
Update users table

### ISSUE THREAD

**Issue by railto** [SimpleLance/SimpleLance#67]
Need to update users table to ensure all following fields are included.  Should also be on users.create and users.edit

First Name*
Last Name*
Address 1*
Address 2
City*
State*
Country* (Possibly a drop down(tho not sure on where to pull the list from))
Phone Number*
Email Address*

Also, if possible, would like to drop the username column, or have it automatically generate as a concatenation of first name and last name (including a space)

**Comment by railto** [comment]
Also need to update the password change mechanism to only require original password if password is being changed by the user.  Should not be required if password is being reset by an admin (kinda impossible for an admin to reset the password otherwise as they would not know the password.)

**Comment by svpernova09** [comment]
These fields have been added. You should be able to edit users without having to update their password now. I believe what was happening was the form validator was choking on something but it wasn't showing the errors on the edit form.
