### ISSUE TITLE
Different views for ticket statuses

### ISSUE THREAD

**Issue by railto** [SimpleLance/SimpleLance#76]
Should update tickets.index so that by default it only shows tickets that are in an open status.  Would then have some sort of selector, be it a dropdown or links for selecting the other ticket statuses.

Also need to make sure that the least recently updated ticket is at the top of the listing for each status, ie tickets that have just received a reply/been updated should be at the bottom of the pile.

**Comment by svpernova09** [comment]
All set. I swapped description to updated at column since that seems to make more sense. Also added a couple methods to allow us to do filtering via /tickets/status/{status title} and added buttons to easily jump between status filters
