### ISSUE TITLE
Public Beta Blockers

### ISSUE THREAD

**Issue by railto** [SimpleLance/SimpleLance#79]
#66 - Updates to Invoices
~~#76 - Different Views for ticket statuses~~
~~#77 - Different Views for project statuses~~
~~#59 - Add replies (conversation) to projects~~
#55 - Full documentation
#80 - Email Alerts

**Comment by svpernova09** [comment]
![image](https://cloud.githubusercontent.com/assets/967362/6042998/e91d87d6-ac4e-11e4-879f-9d8adabea69f.png)


I'll see myself out...

**Comment by railto** [comment]
#66 - Updates to Invoices
#76 - Different Views for ticket statuses
#77 - Different Views for project statuses
#59 - Add replies (conversation) to projects
#55 - Full documentation
